<?php

use App\Http\Controllers\AddressController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\AdminLogController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\DiscountController;
use App\Http\Controllers\HistoryController;
use App\Http\Controllers\NewsController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\SettingsController;
use App\Http\Controllers\SlideController;
use App\Http\Controllers\UserController;

Route::post("/user/signup", [UserController::class, "signup"]);
Route::post("/user/login", [UserController::class, "login"]);
Route::post("/user/verify-email", [UserController::class, "verifyEmail"]);
Route::post("/admin/login", [AdminController::class, "login"]);
Route::get("/contact-us-info", [SettingsController::class, "get_contact_us"]);
Route::get("/about-us", [SettingsController::class, "get_about_us"]);
Route::match(["GET", "POST"], "/guest/categories", [CategoryController::class, "get"]);
Route::get("/guest/most-sold-products", [ProductController::class, "most_sold"]);
Route::get("/guest/product-per-category", [ProductController::class, "one_per_category"]);
Route::get("/guest/home-page", [ProductController::class, "show_in_home_page"]);
Route::get("/guest/contact-us", [SettingsController::class, "get_contact_us"]);
Route::get("/guest/sub-info", [SettingsController::class, "sub_info"]);
Route::get("/guest/slides", [SlideController::class, "getActive"]);
Route::get("guest/news", [NewsController::class, "get"]);
Route::match(["GET", "POST"], "/get-products", [ProductController::class, "get"]);
Route::get("/get-discounts", [DiscountController::class, "get"]);
Route::get("/get-discount-by-code/{code}", [DiscountController::class, "get_by_code"]);
Route::get("/guest/product/{id}", [ProductController::class, "getById"]);

Route::middleware(['auth:user'])->group(function () {
    Route::get("/user-by-token", [UserController::class, "getByToken"]);
    Route::put("/update-info", [UserController::class, "update_info"]);
    Route::put("/change-user-password/{id}", [UserController::class, "changePassword"]);
    Route::post("/create-address", [AddressController::class, "store"]);
    Route::get("/get-addresses", [AddressController::class, "getById"]);
    Route::put("/update-address/{id}", [AddressController::class, "update"]);
    Route::delete("/delete-address/{id}", [AddressController::class, "destroy"]);
    Route::post('/add-to-cart', [CartController::class, "add_to_cart"]);
    Route::delete('/remove-from-cart/{id}', [CartController::class, "remove_from_cart"]);
    Route::post('/apply-discount-to-cart', [CartController::class, "apply_discount"]);
    Route::post("/set-address/{id}", [CartController::class, "set_address"]);
    Route::get('/cart', [CartController::class, "get_cart"]);
    Route::post('/submit-order', [CartController::class, "submit_order"]);
    Route::get('/orders', [CartController::class, "get_orders"]);
    Route::get('/order/{id}', [CartController::class, "get_order_by_id"]);
    Route::post('/contact-us', [ContactController::class, "store"]);
});
Route::middleware(['auth:admin'])->group(function () {
    Route::post("/add-category", [CategoryController::class, "add"]);
    Route::put("/update-category/{id}", [CategoryController::class, "update"]);
    Route::get("/get-category-by-id/{id}", [CategoryController::class, "getById"]);
    Route::post("/get-categories", [CategoryController::class, "get"]);
    Route::delete("/delete-category/{id}", [CategoryController::class, "destroy"]);
    Route::match(['post', 'options'], "/create-product", [ProductController::class, "store"]);
    Route::match(['post', 'options'], "/update-product/{id}", [ProductController::class, "update"]);
    Route::delete("/soft-delete-product/{id}", [ProductController::class, "softDelete"]);
    Route::delete("/restore-product/{id}", [ProductController::class, "restore"]);
    Route::delete("/force-delete-product/{id}", [ProductController::class, "destroy"]);
    Route::get("/get-product-by-id/{id}", [ProductController::class, "getById"]);
    Route::get("/get-trashed-products", [ProductController::class, "get_trashed"]);
    Route::post("/create-discount", [DiscountController::class, "store"]);
    Route::get("/get-discounts-trashed", [DiscountController::class, "trashed_discounts"]);
    Route::get("/get-discount/{id}", [DiscountController::class, "get_by_id"]);
    Route::put("/update-discount/{id}", [DiscountController::class, "update"]);
    Route::delete('/soft-delete-discount/{id}', [DiscountController::class, "softDelete"]);
    Route::delete('/restore-discount/{id}', [DiscountController::class, "restore"]);
    Route::delete("/force-delete-discount/{id}", [DiscountController::class, "destroy"]);
    Route::get('/get-history', [HistoryController::class, "get"]);
    Route::get('/admin/orders', [CartController::class, "get_orders_admin"]);
    Route::get('/admin/order/{id}', [CartController::class, "get_order_by_id_admin"]);
    Route::put('/update-order-status/{id}', [CartController::class, "update_order"]);
    Route::get('/users', [UserController::class, "get"]);
    Route::get('/admin/user/{id}', [UserController::class, "get_by_id"]);
    Route::put("/update-user/{id}", [UserController::class, "update"]);
    Route::get("/addresses", [AddressController::class, "get"]);
    Route::post("/create-news", [NewsController::class, "store"]);
    Route::post("/update-news/{id}", [NewsController::class, "update"]);
    Route::get("/news", [NewsController::class, "get"]);
    Route::get("/get-news/{id}", [NewsController::class, "get_by_id"]);
    Route::delete("/delete-news/{id}", [NewsController::class, "destroy"]);
    Route::get('/admin/contact-us', [ContactController::class, "get"]);
    Route::get('/admin/get-contact-us/{id}', [ContactController::class, "get_by_id"]);
    Route::put("/update-contact-us", [SettingsController::class, "update_contact_us"]);
    Route::match(["PUT", "POST"], "/update-about-us", [SettingsController::class, "update_about_us"]);
    Route::post("/create-slide", [SlideController::class, "store"]);
    Route::put("/update-slide/{id}", [SlideController::class, "update"]);
    Route::delete("/delete-slide/{id}", [SlideController::class, "destroy"]);
    Route::get("/get-slide/{id}", [SlideController::class, "getById"]);
    Route::get("/get-slides", [SlideController::class, "get"]);
    Route::get('/admin/logs', [AdminLogController::class, "get"]);
    Route::get('/admin/log/{id}', [AdminLogController::class, "get_by_id"]);
});
